language: csharp
mono: none
dotnet: 2.1
dist: trusty
env:  
  - CLI_VERSION=latest
script:
 - dotnet --version
 - dotnet pack ./Synker.Scheduled.HostedServices/Synker.Scheduled.HostedServices.csproj -o ./out -c Release /p:PackageVersion="1.0.${TRAVIS_BUILD_NUMBER}"
 - dotnet nuget push ./Synker.Scheduled.HostedServices/out/ -k "${NUGET_API_KEY}" -s https://api.nuget.org/v3/index.json
branches:  
  only:
    - master