language: csharp
mono: none
dotnet: 2.1
dist: trusty
env:  
  - CLI_VERSION=latest
script:
 - dotnet version
 - dotnet pack -o ./out
 - dotnet nuget push ./out -k ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json /p:PackageVersion="1.0.${TRAVIS_BUILD_NUMBER}"
branches:  
  only:
    - master